<?php

namespace AppBundle\Repository;

/**
 * AssessmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
