<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryAllCategories()
    {
        return $this->createQueryBuilder('c')
            ->addOrderBy('c.createdAt','DESC')
            ->leftJoin('c.categoryname','categoryname')
            ->addSelect('categoryname')
            ->getQuery()
            ;
    }

    public function allCategories()
    {
        return $this->queryAllCategories()->execute();
    }
}
