<?php

namespace AppBundle\Repository;

/**
 * imageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryAllimages()
    {
        return $this->createQueryBuilder('i')
            ->addOrderBy('i.createdAt','DESC')
            ->leftJoin('i.imageName','imageName')
            ->addSelect('imageName')
            ->getQuery()
            ;
    }

    public function allImages()
    {
        return $this->queryAllimages()->execute();
    }

}
