<?php

namespace AppBundle\Repository;

/**
 * MessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryAllMessages()
    {
        return $this->createQueryBuilder('m')
            ->addOrderBy('m.createdAt','DESC')
            ->leftJoin('m.issue','issue')
            ->addSelect('issue')
            ->addOrderBy('m.content','DESC')
            ->leftJoin('m.content','content')
            ->addSelect('content')
            ->getQuery()
            ;
    }

    public function allMessages()
    {
        return $this->queryAllMessages()->execute();
    }

    public function queryMessagesByUserId($id)
    {
        $query = $this->createQueryBuilder('m')
            ->leftJoin('m.users','users')
            //->addSelect('users')

            //->addSelect('users2')
            ->addOrderBy('m.createdAt','DESC')
            ->andWhere('users.id = :id')

            ->setParameter('id',$id)
            ->getQuery()
        ;

        //var_dump($query->getDQL());die;
        //var_dump($query->getSQL());die;

        return $query;


    }
    public function messagesByUserId($id)
    {
        return $this->queryMessagesByUserId($id)->execute();
    }

    public function queryMessagesByUserId2($id2)
    {
        $query = $this->createQueryBuilder('m')
            ->leftJoin('m.users2','users2')
            //->addSelect('users2')
            ->addOrderBy('m.createdAt','DESC')
            ->andWhere('users2.id = :id')

            ->setParameter('id',$id2)
            ->getQuery()
        ;

        //var_dump($query->getDQL());die;
        //var_dump($query->getSQL());die;

        return $query;


    }
    public function messagesByUserId2($id2)
    {
        return $this->queryMessagesByUserId2($id2)->execute();
    }

}
