<?php

namespace AppBundle\Repository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryAllProducts()
    {
        return $this->createQueryBuilder('p')
        ->addOrderBy('p.createdAt','DESC')
        ->leftJoin('p.categories','categories')
            ;
    }
    public function allArticles()
    {
        return $this->queryAllProducts()->execute();
    }

    public function queryProductsByCategoryId($id)
    {
        $query = $this->createQueryBuilder('p')
        ->leftJoin('p.categories','categories')
        ->leftJoin('p.imageName','imageName')
        //->addSelect('categories')
        ->addOrderBy('p.createdAt','DESC')
        ->andWhere('categories.id = :id')
        ->setParameter('id',$id)
        ->getQuery()
        ;

        //var_dump($query->getDQL());die;
        //var_dump($query->getSQL());die;

        return $query;
    }

    public function productsByCategoryId($id)
    {
        return $this->queryProductsByCategoryId($id)->execute();
    }

}
