user:
    resource: "@UserBundle/Resources/config/routing.yml"
app.index:
    resource: "@AppBundle/Controller/IndexController.php"
    type: annotation
app.products:
    resource: "@AppBundle/Controller/ProductsController.php"
    type: annotation
app.messages:
    resource: "@AppBundle/Controller/MessagesController.php"
    type: annotation
app.category:
    resource: "@AppBundle/Controller/CategoryController.php"
    type : annotation
